Refactor/HDF-95 Refactor Rewards worker to import halo-rewards contracts via git submodule
HaloDAO/rewards-worker pull request #2
Opened 2021-04-09 10:27 UTC by mystbrent

## Description of Changes

Before this update, the repository explicitly includes halo-reward contracts to the source code to instantiate the Rewards contract. This can be improved by using git submodules to easily reference the halo-rewards contracts to its github repository counterpart.

Added changes also include:

[x] Add postinstall npm script to `package.json` to auto install `halo-rewards` submodule deps
[x] Make use of typescript path module aliases when importing halo-rewards repo to source code

With regards to deriving the signer account from only mnemonic option, I think it limits the option for the worker runner to only one option of using mnemonic. This update also includes resolving that issue by prioritizing the requirement of private key first before mnemonic. This way local tests can easily be done without having to do much effort.

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-95)

## How To Test

### Developer Checklist:

- [x] I have followed the guidelines in our Contributing document
- [x] This PR has a corresponding JIRA ticket
- [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
- [x] I have written new tests for your core changes, as applicable
- [x] I have successfully ran tests locally
- [x] I have formatted my code using format document in VSCode

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
- [ ] I have successfully ran tests locally

2021-04-10 04:25 UTC, tracyarciaga requested changes

2021-04-10 04:25 UTC, tracyarciaga commented on .gitmodules
> +	url = git@github.com:HaloDAO/halo-rewards.git
Please change url = https://github.com/HaloDAO/halo-rewards.git so that it uses https instead of ssh.

2021-04-10 05:18 UTC, bitcoinbrisbane commented on .gitmodules
> +	url = git@github.com:HaloDAO/halo-rewards.git
I use `SSH`

2021-04-10 05:21 UTC, bitcoinbrisbane approved these changes

2021-04-16 09:54 UTC, ctverceles reviewed
@mystbrent does this happen on your local? 
![image](https://user-images.githubusercontent.com/16344192/115006417-6f769180-9edb-11eb-8022-4e81e9013311.png)

On kovan, im getting the same gas estimation err that i got on https://github.com/HaloDAO/pool-worker/pull/2#pullrequestreview-635220634 
![image](https://user-images.githubusercontent.com/16344192/115007618-c4ff6e00-9edc-11eb-9e95-ef28505f7849.png)

2021-04-19 02:21 UTC, ctverceles commented
As of this morning I still get the `revert ERC20: transfer to the zero address` error. 
![image](https://user-images.githubusercontent.com/16344192/115172873-b1c8ea00-a0f8-11eb-8b67-46f01d57657e.png)

on Kovan, 
![image](https://user-images.githubusercontent.com/16344192/115172894-bb525200-a0f8-11eb-8998-ad32fd7376bc.png)

I guess since that kovan err that was happening last week on https://github.com/HaloDAO/pool-worker/pull/2 is now resolved (kovan has moods) and this also has an err on local, then we can try checking whether or not this kovan err is related to the local err and not the kovan network itself @mystbrent

2021-04-19 02:48 UTC, mystbrent commented
Local is working good here. There must be something causing the issue

![image](https://i.imgur.com/58KKh7g.png)

2021-04-19 02:50 UTC, mystbrent commented
Note: Kovan errors have been concluded to be a product of Kovan network issues.

2021-04-19 03:49 UTC, mystbrent commented
Found cause of local error its because there was no setHaloChest call during the deploy instructions in deployAllLocal.

2021-04-19 08:42 UTC, mystbrent commented
Updated to use halo-rewards submodule PR:
https://github.com/HaloDAO/halo-rewards/pull/14

Will test for approval

2021-04-20 05:26 UTC, ctverceles commented
@mystbrent works on my local
<img width="873" alt="Screen Shot 2021-04-20 at 1 17 31 PM" src="https://user-images.githubusercontent.com/16344192/115341873-e95c9280-a1db-11eb-9b0f-933cab7334a2.png">
<img width="748" alt="Screen Shot 2021-04-20 at 1 17 37 PM" src="https://user-images.githubusercontent.com/16344192/115341890-f11c3700-a1db-11eb-84cf-de5e1f6e8261.png">

and works on kovan! https://kovan.etherscan.io/address/0xe37b0E26d6f52ee36edF8a88Fbba7c532EC47Bd9

all good my end to merge!

2021-04-20 05:42 UTC, mystbrent commented
Bumped halo-rewards submodule to https://github.com/HaloDAO/halo-rewards/commit/6e9b368de3e4cd4bbd4e76aab887360268d26433.

2021-04-20 05:42 UTC, merged